<?php
    $this->pageTitle = Yii::app()->name . ' - About Us';
    $this->breadcrumbs = array('About');
?>

<h1>About Us</h1>

<p>TRGRware is a new way to schedule campaigns for Digital Out Of Home (DOOH) – by triggers - and to provide clients improved analytics and reporting.</p>
<p>TRGRware delivers a flexible SaaS platform which allows one-stop-shop for monitor almost any web signal, and utilizing a simple interface to intelligently schedule your campaigns at the right time, the right place and with the creative that most powerfully fits the circumstance.</p>
<p>Triggers are mechanisms to define, monitor and invoke action based on social, weather, traffic, national news stories, keywords, local and global trends conditions and others. Triggers are signals (conditions) defined by the ad-campaign-creator (advertiser, network owner, and advertising agency) as part of the campaign workflow, offloaded to a monitoring entity via API and in return invoked when the monitored conditions are met. As such, one can create a campaign that dynamically responds (changes) as the public response to the campaign changes.</p>
<p style="margin: 0 0 5px;">Here are a few examples:</p>
<ul>
    <li>As traffic nearby an outdoor sign grinds to a halt, there are more attentive eyeballs gazing at it. Clearly as you stand in traffic you are prone to better process the information displayed. As such one can speed up the “round robin” carousel or change the creative to one that’s willing to pay higher premium for pristine exposure.</li>
    <li>Imagine an accident occurs in a small radius near an outdoor sign. Vehicle rolling into the sign’s line of site are witness to sirens whizzing by and all the common sights of an accident scene. This makes many of us think “what if it was me” – a state of mind that enhances the impact of a life insurance campaign or car insurer message etc.</li>
    <li>Ability to monitor social streams in the geo location surrounding an outdoor sign (or group of signs which partake in same campaign) enables to incorporate closed feedback loop (using hashtag tweets for example) to create a dynamic campaign that changes creative as number of response/related tweets increase above a pre-determined threshold. Example: a weekend’s special price rollback of $5/10/20 promised as number of tweets about the campaign, generated by the crowds, increases. As such, crowd sourcing of campaigns becomes real and viral (the effects of this happening in real time as people respond in a group environment). So once (say) 50,000 people tweetted, the price goes down $20 for the weekend.</li>
    <li>Context driven triggers for campaigns can further enhance campaign’s impact and ROI. Example: it makes more sense to stream a Katy Perry billboard ad to a digital sign near Madison Square Gardens, in the few hours leading to and following a concert of say John Mayer or Justin Bibber as the same “kind” of crowd is heading from/to the arena. Much more than doing so arbitrarily “at night time” when shows are playing – simply b/c if the same night Elton John is playing, chances are his fans are not buying a Katy Perry ticket…</li>
    <li>Weather driven campaigns, too, help increase impact. For example – giving Sport Chalet’s Ski ads more exposure as local weather drops and snow conditions start to form, lends itself to far greater success than “spreading” their ad budget evenly all over the place.</li>
</ul>
